name: js-calc-backend

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build the Docker image
      run: |
        ls -l
        cd apps/js-calc-backend
        ls -l
        echo "Running docker build"
        docker build . --tag denniszielke/js-calc-backend:latest
        echo "Pushing image"
        docker push denniszielke/js-calc-backend:latest
        echo "Done"
