name: go-calc-backend

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
      run: |
        ls -l
        cd apps/go-calc-backend
        echo "Docker login"
        echo "Running docker build"
        docker build .  --tag denniszielke/go-calc-backend:latest
        echo "Pushing image"
        docker push denniszielke/go-calc-backend:latest
        echo "Done"
